# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ERPQ
                                 A QGIS plugin
 EISeg remote sensing plug-in in QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-11-03
        copyright            : (C) 2021 by geoyee
        email                : geoyee@yeah.net
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ERPQ class from file ERPQ.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ERPQ import ERPQ
    return ERPQ(iface)
